server:
  port: 8097

spring:
  application:
    name: discount-service

  datasource:
    url: jdbc:mysql://localhost:3308/orches_discount?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
system-url:
  find-user-by-id: http://localhost:9095/users/{userId}