server:
  port: 9093


spring:
  datasource:
    url: jdbc:mysql://localhost:3308/orches_payment?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
logging:
  level:
    org.axonframework: INFO
    io.axoniq.axonserver: INFO
axon:
  axonserver:
    servers: localhost:8124
    configuration:
      shards: 1axon
      context: default

