server:
  port: 9095
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/orches_user?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
axon:
  axonserver:
    servers: localhost:8124
    configuration:
      shards: 1axon
      context: default