server:
  port: 9091
system-url:
  check-valid-voucher: http://localhost:8097/discount/voucher/check/{voucherId}
  find-product-by-id: http://localhost:8093/products/{productId}
  find-user-by-id: http://localhost:9095/users/{userId}

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/orches_order?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
  kafka:
    bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
    topic-send-mail-message: message-created-order
    producer:
      bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org.axonframework: INFO
    io.axoniq.axonserver: INFO
axon:
  axonserver:
    servers: localhost:8124
    configuration:
      shards: 1axon
      context: default




